// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaE3OPglUv-NfNc7Ur4EvwpLj4QN8f45M',
    appId: '1:398396733742:web:3a8ec7476750ef4cf4e2bf',
    messagingSenderId: '398396733742',
    projectId: 'dummyproject-bce33',
    authDomain: 'dummyproject-bce33.firebaseapp.com',
    storageBucket: 'dummyproject-bce33.firebasestorage.app',
    measurementId: 'G-ERCMGTEVNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQrVdE0UdQ_XRo8B5X78tTQTblRUyU8-k',
    appId: '1:398396733742:android:bdc681564d209c89f4e2bf',
    messagingSenderId: '398396733742',
    projectId: 'dummyproject-bce33',
    storageBucket: 'dummyproject-bce33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfXuf_4_R64VwgwkxKunF1rJOEyDbpMhI',
    appId: '1:398396733742:ios:a2cf4b3ff1cf2b01f4e2bf',
    messagingSenderId: '398396733742',
    projectId: 'dummyproject-bce33',
    storageBucket: 'dummyproject-bce33.firebasestorage.app',
    androidClientId: '398396733742-34nvsnq5j4su6nbh4fpb8pjbfi0kas4r.apps.googleusercontent.com',
    iosClientId: '398396733742-3c8jincesrrp6qtl7i3ahnek2efj6cjm.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfXuf_4_R64VwgwkxKunF1rJOEyDbpMhI',
    appId: '1:398396733742:ios:a2cf4b3ff1cf2b01f4e2bf',
    messagingSenderId: '398396733742',
    projectId: 'dummyproject-bce33',
    storageBucket: 'dummyproject-bce33.firebasestorage.app',
    androidClientId: '398396733742-34nvsnq5j4su6nbh4fpb8pjbfi0kas4r.apps.googleusercontent.com',
    iosClientId: '398396733742-3c8jincesrrp6qtl7i3ahnek2efj6cjm.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaE3OPglUv-NfNc7Ur4EvwpLj4QN8f45M',
    appId: '1:398396733742:web:460dbaebe2f273bbf4e2bf',
    messagingSenderId: '398396733742',
    projectId: 'dummyproject-bce33',
    authDomain: 'dummyproject-bce33.firebaseapp.com',
    storageBucket: 'dummyproject-bce33.firebasestorage.app',
    measurementId: 'G-Y3MXYVQ5FR',
  );
}
